title: Humanities & Data Science
logo: /assets/img/humanities_ds_jigsaw.jpg
email: jl.liam.gao@gmail.com
description: Humanities and Data Science working group in the UK.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/had-uk

navigation:
  - name: Introduction
    link: ./index.md
  - name: Members
    link: ./members.md
  - name: Aims
    link: ./aims.md
