title: Humanities & Data Science Group
logo: /assets/img/humanities_ds_jigsaw.png
email: 
description: An independent research group advancing computational approaches in humanities scholarship. Building on the legacy of the Turing Institute's Humanities and Data Science special interest group.
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/had-uk

navigation:
  - name: Introduction
    link: ./index.html
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Aims
    link: ./aims.html
  - name: Talking Points
    link: ./talking_points.html
  - name: Convenors
    link: ./convenors.html
  - name: Members
    link: ./members.html
